ANIMALS = ['Snake', 'Lizard']

rule all:
    input:
        expand('{animal}SizeBar.png', animal=ANIMALS), expand('{animal}SizeBox.png', animal=ANIMALS)
          
rule get_data:
  output:
    '{animal}Sizes.csv'
  script:
    'Make-Data.R'
    
rule make_boxplot:
  input:
    '{animal}Sizes.csv'
  output:
    '{animal}SizeBox.png'
  script:
    'Make-BoxPlot.R'
    
rule make_barplot:
  input:
    '{animal}Sizes.csv'
  output:
    '{animal}SizeBar.png'
  script:
    'Make-BarPlot.R'
    